#! /bin/sh
### BEGIN INIT INFO
# Provides:          cctv
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raspberry pi as cctv
### END INIT INFO
# /etc/init.d/cctv
#

start(){
  echo "starting cctv"
  python /home/pi/cctv.py&
}
stop(){
  echo "stopping cctv"
  pkill -o -f python.*/cctv.py #ps -eaf #for further diagnosis
}
case "$1" in
  stop)
    stop
    ;;
  start|restart|reload)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/cctv {start|stop|restart|reload}"
    exit 1
    ;;
esac

exit 0


# to install
# sudo chmod 755 /etc/init.d/cctv
# sudo update-rc.d cctv defaults

# to start
# sudo service cctv start

# to stop
# sudo service cctv stop

# to uninstall
# sudo update-rc.d cctv remove